
export { default as myArray16 } from './movie/1.mp4';
export { default as myArray26 } from './movie/2.mp4';
export { default as myArray36 } from './movie/3.mp4';
export { default as myArray46 } from './movie/4.mp4';
export { default as myArray56 } from './movie/5.mp4';
export { default as myArray66 } from './movie/6.mp4';
export { default as myArray76 } from './movie/7.mp4';
export { default as myArray86 } from './movie/8.mp4';
export { default as myArray96 } from './movie/9.mp4';
export { default as myArray106 } from './movie/10.mp4';
export { default as myArray116 } from './movie/11.mp4';
export { default as myArray126 } from './movie/12.mp4';
export { default as myArray136 } from './movie/13.mp4';
export { default as myArray146 } from './movie/14.mp4';
export { default as myArray156 } from './movie/15.mp4';
export { default as myArray166 } from './movie/16.mp4';
export { default as myArray176 } from './movie/17.mp4';
export { default as myArray186 } from './movie/18.mp4';
export { default as myArray196 } from './movie/19.mp4';

export { default as myArray18 } from './image/1.jpg';
export { default as myArray28 } from './image/2.jpg';
export { default as myArray38 } from './image/3.jpg';
export { default as myArray48 } from './image/4.jpg';
export { default as myArray58 } from './image/5.jpg';
export { default as myArray68 } from './image/6.jpg';
export { default as myArray78 } from './image/7.jpg';
export { default as myArray88 } from './image/8.jpg';
export { default as myArray98 } from './image/9.jpg';
export { default as myArray108} from './image/10.jpg';
export { default as myArray118} from './image/11.jpg';
export { default as myArray128 } from './image/12.jpg';
export { default as myArray138 } from './image/13.jpg';
export { default as myArray148 } from './image/14.jpg';
export { default as myArray158 } from './image/15.jpg';
export { default as myArray168 } from './image/16.jpg';
export { default as myArray178 } from './image/17.jpg';
export { default as myArray188 } from './image/18.jpg';
export { default as myArray198 } from './image/19.jpg';
